// GENERATED by slang-bindgen from api/slang-api.json (Slang 2026.13). DO NOT EDIT.
// Regenerate: see CLAUDE.md / DESIGN.md §9.
package io.github.refux.slang;

import io.github.refux.slang.ffi.SlangNative;
import io.github.refux.slang.ffi.gen.SlangReflectionAPI;
import java.lang.foreign.Arena;
import java.lang.foreign.MemorySegment;

/**
 * Generated base of {&#64;code slang::Attribute}: each method forwards to the spReflection* downcall that slang.h's inline C++ wrapper compiles to. Reflection data is owned by the component/session it came from; the {&#64;code owner} reference keeps that owner reachable. The hand-written subclass {&#64;code Attribute} adds ergonomics.
 */
public abstract class AttributeGen {
    final MemorySegment self;
    final Object owner;

    AttributeGen(MemorySegment self, Object owner) {
        this.self = self;
        this.owner = owner;
    }

    /** The raw native reflection pointer (borrowed; owned by the program). */
    public final MemorySegment segment() {
        return self;
    }

    /** Calls {@code spReflectionUserAttribute_GetArgumentCount}. */
    public int getArgumentCount() {
        return SlangReflectionAPI.spReflectionUserAttribute_GetArgumentCount(self);
    }

    /** Calls {@code spReflectionUserAttribute_GetArgumentType}. */
    public TypeReflection getArgumentType(int index) {
        MemorySegment result = SlangReflectionAPI.spReflectionUserAttribute_GetArgumentType(self, index);
        return result.address() == 0 ? null : new TypeReflection(result, owner);
    }

    /** Calls {@code spReflectionUserAttribute_GetArgumentValueFloat}. */
    public int getArgumentValueFloat(int index, MemorySegment rs) {
        return SlangReflectionAPI.spReflectionUserAttribute_GetArgumentValueFloat(self, index, rs);
    }

    /** Calls {@code spReflectionUserAttribute_GetArgumentValueInt}. */
    public int getArgumentValueInt(int index, MemorySegment rs) {
        return SlangReflectionAPI.spReflectionUserAttribute_GetArgumentValueInt(self, index, rs);
    }

    /** Calls {@code spReflectionUserAttribute_GetArgumentValueString}. */
    public String getArgumentValueString(int index, MemorySegment outSize) {
        return SlangNative.readUtf8(SlangReflectionAPI.spReflectionUserAttribute_GetArgumentValueString(self, index, outSize));
    }

    /** Calls {@code spReflectionUserAttribute_GetName}. */
    public String getName() {
        return SlangNative.readUtf8(SlangReflectionAPI.spReflectionUserAttribute_GetName(self));
    }

}
