// GENERATED by slang-bindgen from api/slang-api.json (Slang 2026.13). DO NOT EDIT.
// Regenerate: see CLAUDE.md / DESIGN.md §9.
package io.github.refux.slang;

import io.github.refux.slang.ffi.SlangNative;
import io.github.refux.slang.ffi.gen.SlangReflectionAPI;
import java.lang.foreign.Arena;
import java.lang.foreign.MemorySegment;

/**
 * Generated base of {&#64;code slang::DeclReflection}: each method forwards to the spReflection* downcall that slang.h's inline C++ wrapper compiles to. Reflection data is owned by the component/session it came from; the {&#64;code owner} reference keeps that owner reachable. The hand-written subclass {&#64;code DeclReflection} adds ergonomics.
 */
public abstract class DeclReflectionGen {
    final MemorySegment self;
    final Object owner;

    DeclReflectionGen(MemorySegment self, Object owner) {
        this.self = self;
        this.owner = owner;
    }

    /** The raw native reflection pointer (borrowed; owned by the program). */
    public final MemorySegment segment() {
        return self;
    }

    /** Calls {@code spReflectionDecl_castToFunction}. */
    public FunctionReflection asFunction() {
        MemorySegment result = SlangReflectionAPI.spReflectionDecl_castToFunction(self);
        return result.address() == 0 ? null : new FunctionReflection(result, owner);
    }

    /** Calls {@code spReflectionDecl_castToGeneric}. */
    public GenericReflection asGeneric() {
        MemorySegment result = SlangReflectionAPI.spReflectionDecl_castToGeneric(self);
        return result.address() == 0 ? null : new GenericReflection(result, owner);
    }

    /** Calls {@code spReflectionDecl_castToVariable}. */
    public VariableReflection asVariable() {
        MemorySegment result = SlangReflectionAPI.spReflectionDecl_castToVariable(self);
        return result.address() == 0 ? null : new VariableReflection(result, owner);
    }

    /** Calls {@code spReflectionDecl_findModifier}. */
    public MemorySegment findModifier(int modifierID) {
        return SlangReflectionAPI.spReflectionDecl_findModifier(self, modifierID);
    }

    /** Calls {@code spReflectionDecl_getChild}. */
    public DeclReflection getChild(int index) {
        MemorySegment result = SlangReflectionAPI.spReflectionDecl_getChild(self, index);
        return result.address() == 0 ? null : new DeclReflection(result, owner);
    }

    /** Calls {@code spReflectionDecl_getChildrenCount}. */
    public int getChildrenCount() {
        return SlangReflectionAPI.spReflectionDecl_getChildrenCount(self);
    }

    /** Calls {@code spReflectionDecl_getKind}. */
    public int getKind() {
        return SlangReflectionAPI.spReflectionDecl_getKind(self);
    }

    /** Calls {@code spReflectionDecl_getName}. */
    public String getName() {
        return SlangNative.readUtf8(SlangReflectionAPI.spReflectionDecl_getName(self));
    }

    /** Calls {@code spReflectionDecl_getParent}. */
    public DeclReflection getParent() {
        MemorySegment result = SlangReflectionAPI.spReflectionDecl_getParent(self);
        return result.address() == 0 ? null : new DeclReflection(result, owner);
    }

    /** Calls {@code spReflection_getTypeFromDecl}. */
    public TypeReflection getType() {
        MemorySegment result = SlangReflectionAPI.spReflection_getTypeFromDecl(self);
        return result.address() == 0 ? null : new TypeReflection(result, owner);
    }

}
