// GENERATED by slang-bindgen from api/slang-api.json (Slang 2026.13). DO NOT EDIT.
// Regenerate: see CLAUDE.md / DESIGN.md §9.
package io.github.refux.slang;

import io.github.refux.slang.ffi.SlangNative;
import io.github.refux.slang.ffi.gen.SlangReflectionAPI;
import java.lang.foreign.Arena;
import java.lang.foreign.MemorySegment;

/**
 * Generated base of {&#64;code slang::EntryPointReflection}: each method forwards to the spReflection* downcall that slang.h's inline C++ wrapper compiles to. Reflection data is owned by the component/session it came from; the {&#64;code owner} reference keeps that owner reachable. The hand-written subclass {&#64;code EntryPointReflection} adds ergonomics.
 */
public abstract class EntryPointReflectionGen {
    final MemorySegment self;
    final Object owner;

    EntryPointReflectionGen(MemorySegment self, Object owner) {
        this.self = self;
        this.owner = owner;
    }

    /** The raw native reflection pointer (borrowed; owned by the program). */
    public final MemorySegment segment() {
        return self;
    }

    /** Calls {@code spReflectionEntryPoint_getComputeThreadGroupSize}. */
    public void getComputeThreadGroupSize(long axisCount, MemorySegment outSizeAlongAxis) {
        SlangReflectionAPI.spReflectionEntryPoint_getComputeThreadGroupSize(self, axisCount, outSizeAlongAxis);
    }

    /** Calls {@code spReflectionEntryPoint_getComputeWaveSize}. */
    public void getComputeWaveSize(MemorySegment outWaveSize) {
        SlangReflectionAPI.spReflectionEntryPoint_getComputeWaveSize(self, outWaveSize);
    }

    /** Calls {@code spReflectionEntryPoint_getFunction}. */
    public FunctionReflection getFunction() {
        MemorySegment result = SlangReflectionAPI.spReflectionEntryPoint_getFunction(self);
        return result.address() == 0 ? null : new FunctionReflection(result, owner);
    }

    /** Calls {@code spReflectionEntryPoint_getName}. */
    public String getName() {
        return SlangNative.readUtf8(SlangReflectionAPI.spReflectionEntryPoint_getName(self));
    }

    /** Calls {@code spReflectionEntryPoint_getNameOverride}. */
    public String getNameOverride() {
        return SlangNative.readUtf8(SlangReflectionAPI.spReflectionEntryPoint_getNameOverride(self));
    }

    /** Calls {@code spReflectionEntryPoint_getParameterByIndex}. */
    public VariableLayoutReflection getParameterByIndex(int index) {
        MemorySegment result = SlangReflectionAPI.spReflectionEntryPoint_getParameterByIndex(self, index);
        return result.address() == 0 ? null : new VariableLayoutReflection(result, owner);
    }

    /** Calls {@code spReflectionEntryPoint_getParameterCount}. */
    public int getParameterCount() {
        return SlangReflectionAPI.spReflectionEntryPoint_getParameterCount(self);
    }

    /** Calls {@code spReflectionEntryPoint_getResultVarLayout}. */
    public VariableLayoutReflection getResultVarLayout() {
        MemorySegment result = SlangReflectionAPI.spReflectionEntryPoint_getResultVarLayout(self);
        return result.address() == 0 ? null : new VariableLayoutReflection(result, owner);
    }

    /** Calls {@code spReflectionEntryPoint_getStage}. */
    public int getStage() {
        return SlangReflectionAPI.spReflectionEntryPoint_getStage(self);
    }

    /** Calls {@code spReflectionEntryPoint_getVarLayout}. */
    public VariableLayoutReflection getVarLayout() {
        MemorySegment result = SlangReflectionAPI.spReflectionEntryPoint_getVarLayout(self);
        return result.address() == 0 ? null : new VariableLayoutReflection(result, owner);
    }

    /** Calls {@code spReflectionEntryPoint_hasDefaultConstantBuffer}. */
    public int hasDefaultConstantBuffer() {
        return SlangReflectionAPI.spReflectionEntryPoint_hasDefaultConstantBuffer(self);
    }

    /** Calls {@code spReflectionEntryPoint_usesAnySampleRateInput}. */
    public int usesAnySampleRateInput() {
        return SlangReflectionAPI.spReflectionEntryPoint_usesAnySampleRateInput(self);
    }

}
