// GENERATED by slang-bindgen from api/slang-api.json (Slang 2026.13). DO NOT EDIT.
// Regenerate: see CLAUDE.md / DESIGN.md §9.
package io.github.refux.slang;

import io.github.refux.slang.ffi.SlangNative;
import io.github.refux.slang.ffi.gen.SlangReflectionAPI;
import java.lang.foreign.Arena;
import java.lang.foreign.MemorySegment;

/**
 * Generated base of {&#64;code slang::FunctionReflection}: each method forwards to the spReflection* downcall that slang.h's inline C++ wrapper compiles to. Reflection data is owned by the component/session it came from; the {&#64;code owner} reference keeps that owner reachable. The hand-written subclass {&#64;code FunctionReflection} adds ergonomics.
 */
public abstract class FunctionReflectionGen {
    final MemorySegment self;
    final Object owner;

    FunctionReflectionGen(MemorySegment self, Object owner) {
        this.self = self;
        this.owner = owner;
    }

    /** The raw native reflection pointer (borrowed; owned by the program). */
    public final MemorySegment segment() {
        return self;
    }

    /** Calls {@code spReflectionFunction_applySpecializations}. */
    public FunctionReflection applySpecializations(GenericReflection generic) {
        MemorySegment result = SlangReflectionAPI.spReflectionFunction_applySpecializations(self, (generic == null ? MemorySegment.NULL : generic.self));
        return result.address() == 0 ? null : new FunctionReflection(result, owner);
    }

    /** Calls {@code spReflectionFunction_FindUserAttributeByName}. */
    public Attribute findAttributeByName(MemorySegment globalSession, String name) {
        try (Arena arena = Arena.ofConfined()) {
            MemorySegment result = SlangReflectionAPI.spReflectionFunction_FindUserAttributeByName(self, globalSession, arena.allocateFrom(name));
            return result.address() == 0 ? null : new Attribute(result, owner);
        }
    }

    /** Calls {@code spReflectionFunction_FindModifier}. */
    public MemorySegment findModifier(int modifierID) {
        return SlangReflectionAPI.spReflectionFunction_FindModifier(self, modifierID);
    }

    /** Calls {@code spReflectionFunction_GetGenericContainer}. */
    public GenericReflection getGenericContainer() {
        MemorySegment result = SlangReflectionAPI.spReflectionFunction_GetGenericContainer(self);
        return result.address() == 0 ? null : new GenericReflection(result, owner);
    }

    /** Calls {@code spReflectionFunction_GetName}. */
    public String getName() {
        return SlangNative.readUtf8(SlangReflectionAPI.spReflectionFunction_GetName(self));
    }

    /** Calls {@code spReflectionFunction_getOverload}. */
    public FunctionReflection getOverload(int index) {
        MemorySegment result = SlangReflectionAPI.spReflectionFunction_getOverload(self, index);
        return result.address() == 0 ? null : new FunctionReflection(result, owner);
    }

    /** Calls {@code spReflectionFunction_getOverloadCount}. */
    public int getOverloadCount() {
        return SlangReflectionAPI.spReflectionFunction_getOverloadCount(self);
    }

    /** Calls {@code spReflectionFunction_GetParameter}. */
    public VariableReflection getParameterByIndex(int index) {
        MemorySegment result = SlangReflectionAPI.spReflectionFunction_GetParameter(self, index);
        return result.address() == 0 ? null : new VariableReflection(result, owner);
    }

    /** Calls {@code spReflectionFunction_GetParameterCount}. */
    public int getParameterCount() {
        return SlangReflectionAPI.spReflectionFunction_GetParameterCount(self);
    }

    /** Calls {@code spReflectionFunction_GetResultType}. */
    public TypeReflection getReturnType() {
        MemorySegment result = SlangReflectionAPI.spReflectionFunction_GetResultType(self);
        return result.address() == 0 ? null : new TypeReflection(result, owner);
    }

    /** Calls {@code spReflectionFunction_GetUserAttribute}. */
    public Attribute getUserAttributeByIndex(int index) {
        MemorySegment result = SlangReflectionAPI.spReflectionFunction_GetUserAttribute(self, index);
        return result.address() == 0 ? null : new Attribute(result, owner);
    }

    /** Calls {@code spReflectionFunction_GetUserAttributeCount}. */
    public int getUserAttributeCount() {
        return SlangReflectionAPI.spReflectionFunction_GetUserAttributeCount(self);
    }

    /** Calls {@code spReflectionFunction_isOverloaded}. */
    public boolean isOverloaded() {
        return SlangReflectionAPI.spReflectionFunction_isOverloaded(self);
    }

    /** Calls {@code spReflectionFunction_specializeWithArgTypes}. */
    public FunctionReflection specializeWithArgTypes(long argTypeCount, MemorySegment argTypes) {
        MemorySegment result = SlangReflectionAPI.spReflectionFunction_specializeWithArgTypes(self, argTypeCount, argTypes);
        return result.address() == 0 ? null : new FunctionReflection(result, owner);
    }

}
