// GENERATED by slang-bindgen from api/slang-api.json (Slang 2026.13). DO NOT EDIT.
// Regenerate: see CLAUDE.md / DESIGN.md §9.
package io.github.refux.slang;

import io.github.refux.slang.ffi.SlangNative;
import io.github.refux.slang.ffi.gen.SlangReflectionAPI;
import java.lang.foreign.Arena;
import java.lang.foreign.MemorySegment;

/**
 * Generated base of {&#64;code slang::ShaderReflection}: each method forwards to the spReflection* downcall that slang.h's inline C++ wrapper compiles to. Reflection data is owned by the component/session it came from; the {&#64;code owner} reference keeps that owner reachable. The hand-written subclass {&#64;code ShaderReflection} adds ergonomics.
 */
public abstract class ShaderReflectionGen {
    final MemorySegment self;
    final Object owner;

    ShaderReflectionGen(MemorySegment self, Object owner) {
        this.self = self;
        this.owner = owner;
    }

    /** The raw native reflection pointer (borrowed; owned by the program). */
    public final MemorySegment segment() {
        return self;
    }

    /** Calls {@code spReflection_findEntryPointByName}. */
    public EntryPointReflection findEntryPointByName(String name) {
        try (Arena arena = Arena.ofConfined()) {
            MemorySegment result = SlangReflectionAPI.spReflection_findEntryPointByName(self, arena.allocateFrom(name));
            return result.address() == 0 ? null : new EntryPointReflection(result, owner);
        }
    }

    /** Calls {@code spReflection_FindFunctionByName}. */
    public FunctionReflection findFunctionByName(String name) {
        try (Arena arena = Arena.ofConfined()) {
            MemorySegment result = SlangReflectionAPI.spReflection_FindFunctionByName(self, arena.allocateFrom(name));
            return result.address() == 0 ? null : new FunctionReflection(result, owner);
        }
    }

    /** Calls {@code spReflection_FindFunctionByNameInType}. */
    public FunctionReflection findFunctionByNameInType(TypeReflection reflType, String name) {
        try (Arena arena = Arena.ofConfined()) {
            MemorySegment result = SlangReflectionAPI.spReflection_FindFunctionByNameInType(self, (reflType == null ? MemorySegment.NULL : reflType.self), arena.allocateFrom(name));
            return result.address() == 0 ? null : new FunctionReflection(result, owner);
        }
    }

    /** Calls {@code spReflection_FindTypeByName}. */
    public TypeReflection findTypeByName(String name) {
        try (Arena arena = Arena.ofConfined()) {
            MemorySegment result = SlangReflectionAPI.spReflection_FindTypeByName(self, arena.allocateFrom(name));
            return result.address() == 0 ? null : new TypeReflection(result, owner);
        }
    }

    /** Calls {@code spReflection_FindTypeParameter}. */
    public TypeParameterReflection findTypeParameter(String name) {
        try (Arena arena = Arena.ofConfined()) {
            MemorySegment result = SlangReflectionAPI.spReflection_FindTypeParameter(self, arena.allocateFrom(name));
            return result.address() == 0 ? null : new TypeParameterReflection(result, owner);
        }
    }

    /** Calls {@code spReflection_FindVarByNameInType}. */
    public VariableReflection findVarByNameInType(TypeReflection reflType, String name) {
        try (Arena arena = Arena.ofConfined()) {
            MemorySegment result = SlangReflectionAPI.spReflection_FindVarByNameInType(self, (reflType == null ? MemorySegment.NULL : reflType.self), arena.allocateFrom(name));
            return result.address() == 0 ? null : new VariableReflection(result, owner);
        }
    }

    /** Calls {@code spReflection_getBindlessSpaceIndex}. */
    public long getBindlessSpaceIndex() {
        return SlangReflectionAPI.spReflection_getBindlessSpaceIndex(self);
    }

    /** Calls {@code spReflection_getEntryPointByIndex}. */
    public EntryPointReflection getEntryPointByIndex(long index) {
        MemorySegment result = SlangReflectionAPI.spReflection_getEntryPointByIndex(self, index);
        return result.address() == 0 ? null : new EntryPointReflection(result, owner);
    }

    /** Calls {@code spReflection_getEntryPointCount}. */
    public long getEntryPointCount() {
        return SlangReflectionAPI.spReflection_getEntryPointCount(self);
    }

    /** Calls {@code spReflection_getGlobalConstantBufferBinding}. */
    public long getGlobalConstantBufferBinding() {
        return SlangReflectionAPI.spReflection_getGlobalConstantBufferBinding(self);
    }

    /** Calls {@code spReflection_getGlobalConstantBufferSize}. */
    public long getGlobalConstantBufferSize() {
        return SlangReflectionAPI.spReflection_getGlobalConstantBufferSize(self);
    }

    /** Calls {@code spReflection_getGlobalParamsTypeLayout}. */
    public TypeLayoutReflection getGlobalParamsTypeLayout() {
        MemorySegment result = SlangReflectionAPI.spReflection_getGlobalParamsTypeLayout(self);
        return result.address() == 0 ? null : new TypeLayoutReflection(result, owner);
    }

    /** Calls {@code spReflection_getGlobalParamsVarLayout}. */
    public VariableLayoutReflection getGlobalParamsVarLayout() {
        MemorySegment result = SlangReflectionAPI.spReflection_getGlobalParamsVarLayout(self);
        return result.address() == 0 ? null : new VariableLayoutReflection(result, owner);
    }

    /** Calls {@code spReflection_getHashedString}. */
    public String getHashedString(long index, MemorySegment outCount) {
        return SlangNative.readUtf8(SlangReflectionAPI.spReflection_getHashedString(self, index, outCount));
    }

    /** Calls {@code spReflection_getHashedStringCount}. */
    public long getHashedStringCount() {
        return SlangReflectionAPI.spReflection_getHashedStringCount(self);
    }

    /** Calls {@code spReflection_GetParameterByIndex}. */
    public VariableLayoutReflection getParameterByIndex(int index) {
        MemorySegment result = SlangReflectionAPI.spReflection_GetParameterByIndex(self, index);
        return result.address() == 0 ? null : new VariableLayoutReflection(result, owner);
    }

    /** Calls {@code spReflection_GetParameterCount}. */
    public int getParameterCount() {
        return SlangReflectionAPI.spReflection_GetParameterCount(self);
    }

    /** Calls {@code spReflection_GetSession}. */
    public MemorySegment getSession() {
        return SlangReflectionAPI.spReflection_GetSession(self);
    }

    /** Calls {@code spReflection_GetTypeLayout}. */
    public TypeLayoutReflection getTypeLayout(TypeReflection reflectionType, int rules) {
        MemorySegment result = SlangReflectionAPI.spReflection_GetTypeLayout(self, (reflectionType == null ? MemorySegment.NULL : reflectionType.self), rules);
        return result.address() == 0 ? null : new TypeLayoutReflection(result, owner);
    }

    /** Calls {@code spReflection_GetTypeParameterByIndex}. */
    public TypeParameterReflection getTypeParameterByIndex(int index) {
        MemorySegment result = SlangReflectionAPI.spReflection_GetTypeParameterByIndex(self, index);
        return result.address() == 0 ? null : new TypeParameterReflection(result, owner);
    }

    /** Calls {@code spReflection_GetTypeParameterCount}. */
    public int getTypeParameterCount() {
        return SlangReflectionAPI.spReflection_GetTypeParameterCount(self);
    }

    /** Calls {@code spReflection_isSubType}. */
    public boolean isSubType(TypeReflection subType, TypeReflection superType) {
        return SlangReflectionAPI.spReflection_isSubType(self, (subType == null ? MemorySegment.NULL : subType.self), (superType == null ? MemorySegment.NULL : superType.self));
    }

    /** Calls {@code spReflection_specializeGeneric}. */
    public GenericReflection specializeGeneric(GenericReflection generic, long argCount, MemorySegment argTypes, MemorySegment args, MemorySegment outDiagnostics) {
        MemorySegment result = SlangReflectionAPI.spReflection_specializeGeneric(self, (generic == null ? MemorySegment.NULL : generic.self), argCount, argTypes, args, outDiagnostics);
        return result.address() == 0 ? null : new GenericReflection(result, owner);
    }

    /** Calls {@code spReflection_specializeType}. */
    public TypeReflection specializeType(TypeReflection type, long specializationArgCount, MemorySegment specializationArgs, MemorySegment outDiagnostics) {
        MemorySegment result = SlangReflectionAPI.spReflection_specializeType(self, (type == null ? MemorySegment.NULL : type.self), specializationArgCount, specializationArgs, outDiagnostics);
        return result.address() == 0 ? null : new TypeReflection(result, owner);
    }

    /** Calls {@code spReflection_ToJson}. */
    public int toJson(MemorySegment request, MemorySegment outBlob) {
        return SlangReflectionAPI.spReflection_ToJson(self, request, outBlob);
    }

    /** Calls {@code spReflection_TryResolveOverloadedFunction}. */
    public FunctionReflection tryResolveOverloadedFunction(int candidateCount, MemorySegment candidates) {
        MemorySegment result = SlangReflectionAPI.spReflection_TryResolveOverloadedFunction(self, candidateCount, candidates);
        return result.address() == 0 ? null : new FunctionReflection(result, owner);
    }

}
