// GENERATED by slang-bindgen from api/slang-api.json (Slang 2026.13). DO NOT EDIT.
// Regenerate: see CLAUDE.md / DESIGN.md §9.
package io.github.refux.slang;

import io.github.refux.slang.ffi.SlangNative;
import io.github.refux.slang.ffi.gen.SlangReflectionAPI;
import java.lang.foreign.Arena;
import java.lang.foreign.MemorySegment;

/**
 * Generated base of {&#64;code slang::TypeParameterReflection}: each method forwards to the spReflection* downcall that slang.h's inline C++ wrapper compiles to. Reflection data is owned by the component/session it came from; the {&#64;code owner} reference keeps that owner reachable. The hand-written subclass {&#64;code TypeParameterReflection} adds ergonomics.
 */
public abstract class TypeParameterReflectionGen {
    final MemorySegment self;
    final Object owner;

    TypeParameterReflectionGen(MemorySegment self, Object owner) {
        this.self = self;
        this.owner = owner;
    }

    /** The raw native reflection pointer (borrowed; owned by the program). */
    public final MemorySegment segment() {
        return self;
    }

    /** Calls {@code spReflectionTypeParameter_GetConstraintByIndex}. */
    public TypeReflection getConstraintByIndex(int index) {
        MemorySegment result = SlangReflectionAPI.spReflectionTypeParameter_GetConstraintByIndex(self, index);
        return result.address() == 0 ? null : new TypeReflection(result, owner);
    }

    /** Calls {@code spReflectionTypeParameter_GetConstraintCount}. */
    public int getConstraintCount() {
        return SlangReflectionAPI.spReflectionTypeParameter_GetConstraintCount(self);
    }

    /** Calls {@code spReflectionTypeParameter_GetIndex}. */
    public int getIndex() {
        return SlangReflectionAPI.spReflectionTypeParameter_GetIndex(self);
    }

    /** Calls {@code spReflectionTypeParameter_GetName}. */
    public String getName() {
        return SlangNative.readUtf8(SlangReflectionAPI.spReflectionTypeParameter_GetName(self));
    }

}
