// GENERATED by slang-bindgen from api/slang-api.json (Slang 2026.13). DO NOT EDIT.
// Regenerate: see CLAUDE.md / DESIGN.md §9.
package io.github.refux.slang;

import io.github.refux.slang.ffi.SlangNative;
import io.github.refux.slang.ffi.gen.SlangReflectionAPI;
import java.lang.foreign.Arena;
import java.lang.foreign.MemorySegment;

/**
 * Generated base of {&#64;code slang::TypeReflection}: each method forwards to the spReflection* downcall that slang.h's inline C++ wrapper compiles to. Reflection data is owned by the component/session it came from; the {&#64;code owner} reference keeps that owner reachable. The hand-written subclass {&#64;code TypeReflection} adds ergonomics.
 */
public abstract class TypeReflectionGen {
    final MemorySegment self;
    final Object owner;

    TypeReflectionGen(MemorySegment self, Object owner) {
        this.self = self;
        this.owner = owner;
    }

    /** The raw native reflection pointer (borrowed; owned by the program). */
    public final MemorySegment segment() {
        return self;
    }

    /** Calls {@code spReflectionType_applySpecializations}. */
    public TypeReflection applySpecializations(GenericReflection generic) {
        MemorySegment result = SlangReflectionAPI.spReflectionType_applySpecializations(self, (generic == null ? MemorySegment.NULL : generic.self));
        return result.address() == 0 ? null : new TypeReflection(result, owner);
    }

    /** Calls {@code spReflectionType_FindUserAttributeByName}. */
    public Attribute findAttributeByName(String name) {
        try (Arena arena = Arena.ofConfined()) {
            MemorySegment result = SlangReflectionAPI.spReflectionType_FindUserAttributeByName(self, arena.allocateFrom(name));
            return result.address() == 0 ? null : new Attribute(result, owner);
        }
    }

    /** Calls {@code spReflectionType_GetColumnCount}. */
    public int getColumnCount() {
        return SlangReflectionAPI.spReflectionType_GetColumnCount(self);
    }

    /** Calls {@code spReflectionType_GetSpecializedElementCount}. */
    public long getElementCount(ShaderReflection reflection) {
        return SlangReflectionAPI.spReflectionType_GetSpecializedElementCount(self, (reflection == null ? MemorySegment.NULL : reflection.self));
    }

    /** Calls {@code spReflectionType_GetElementType}. */
    public TypeReflection getElementType() {
        MemorySegment result = SlangReflectionAPI.spReflectionType_GetElementType(self);
        return result.address() == 0 ? null : new TypeReflection(result, owner);
    }

    /** Calls {@code spReflectionType_GetFieldByIndex}. */
    public VariableReflection getFieldByIndex(int index) {
        MemorySegment result = SlangReflectionAPI.spReflectionType_GetFieldByIndex(self, index);
        return result.address() == 0 ? null : new VariableReflection(result, owner);
    }

    /** Calls {@code spReflectionType_GetFieldCount}. */
    public int getFieldCount() {
        return SlangReflectionAPI.spReflectionType_GetFieldCount(self);
    }

    /** Calls {@code spReflectionType_GetFullName}. */
    public int getFullName(MemorySegment outNameBlob) {
        return SlangReflectionAPI.spReflectionType_GetFullName(self, outNameBlob);
    }

    /** Calls {@code spReflectionType_GetGenericContainer}. */
    public GenericReflection getGenericContainer() {
        MemorySegment result = SlangReflectionAPI.spReflectionType_GetGenericContainer(self);
        return result.address() == 0 ? null : new GenericReflection(result, owner);
    }

    /** Calls {@code spReflectionType_GetKind}. */
    public int getKind() {
        return SlangReflectionAPI.spReflectionType_GetKind(self);
    }

    /** Calls {@code spReflectionType_GetName}. */
    public String getName() {
        return SlangNative.readUtf8(SlangReflectionAPI.spReflectionType_GetName(self));
    }

    /** Calls {@code spReflectionType_GetResourceAccess}. */
    public int getResourceAccess() {
        return SlangReflectionAPI.spReflectionType_GetResourceAccess(self);
    }

    /** Calls {@code spReflectionType_GetResourceResultType}. */
    public TypeReflection getResourceResultType() {
        MemorySegment result = SlangReflectionAPI.spReflectionType_GetResourceResultType(self);
        return result.address() == 0 ? null : new TypeReflection(result, owner);
    }

    /** Calls {@code spReflectionType_GetResourceShape}. */
    public int getResourceShape() {
        return SlangReflectionAPI.spReflectionType_GetResourceShape(self);
    }

    /** Calls {@code spReflectionType_GetRowCount}. */
    public int getRowCount() {
        return SlangReflectionAPI.spReflectionType_GetRowCount(self);
    }

    /** Calls {@code spReflectionType_GetScalarType}. */
    public int getScalarType() {
        return SlangReflectionAPI.spReflectionType_GetScalarType(self);
    }

    /** Calls {@code spReflectionType_GetUserAttribute}. */
    public Attribute getUserAttributeByIndex(int index) {
        MemorySegment result = SlangReflectionAPI.spReflectionType_GetUserAttribute(self, index);
        return result.address() == 0 ? null : new Attribute(result, owner);
    }

    /** Calls {@code spReflectionType_GetUserAttributeCount}. */
    public int getUserAttributeCount() {
        return SlangReflectionAPI.spReflectionType_GetUserAttributeCount(self);
    }

}
