// GENERATED by slang-bindgen from api/slang-api.json (Slang 2026.13). DO NOT EDIT.
// Regenerate: see CLAUDE.md / DESIGN.md §9.
package io.github.refux.slang;

import io.github.refux.slang.ffi.SlangNative;
import io.github.refux.slang.ffi.gen.SlangReflectionAPI;
import java.lang.foreign.Arena;
import java.lang.foreign.MemorySegment;

/**
 * Generated base of {&#64;code slang::VariableLayoutReflection}: each method forwards to the spReflection* downcall that slang.h's inline C++ wrapper compiles to. Reflection data is owned by the component/session it came from; the {&#64;code owner} reference keeps that owner reachable. The hand-written subclass {&#64;code VariableLayoutReflection} adds ergonomics.
 */
public abstract class VariableLayoutReflectionGen {
    final MemorySegment self;
    final Object owner;

    VariableLayoutReflectionGen(MemorySegment self, Object owner) {
        this.self = self;
        this.owner = owner;
    }

    /** The raw native reflection pointer (borrowed; owned by the program). */
    public final MemorySegment segment() {
        return self;
    }

    /** Calls {@code spReflectionParameter_GetBindingIndex}. */
    public int getBindingIndex() {
        return SlangReflectionAPI.spReflectionParameter_GetBindingIndex(self);
    }

    /** Calls {@code spReflectionParameter_GetBindingSpace}. */
    public int getBindingSpace() {
        return SlangReflectionAPI.spReflectionParameter_GetBindingSpace(self);
    }

    /** Calls {@code spReflectionVariableLayout_GetSpace}. */
    public long getBindingSpace(int category) {
        return SlangReflectionAPI.spReflectionVariableLayout_GetSpace(self, category);
    }

    /** Calls {@code spReflectionVariableLayout_GetImageFormat}. */
    public int getImageFormat() {
        return SlangReflectionAPI.spReflectionVariableLayout_GetImageFormat(self);
    }

    /** Calls {@code spReflectionVariableLayout_GetOffset}. */
    public long getOffset(int category) {
        return SlangReflectionAPI.spReflectionVariableLayout_GetOffset(self, category);
    }

    /** Calls {@code spReflectionVariableLayout_GetSemanticIndex}. */
    public long getSemanticIndex() {
        return SlangReflectionAPI.spReflectionVariableLayout_GetSemanticIndex(self);
    }

    /** Calls {@code spReflectionVariableLayout_GetSemanticName}. */
    public String getSemanticName() {
        return SlangNative.readUtf8(SlangReflectionAPI.spReflectionVariableLayout_GetSemanticName(self));
    }

    /** Calls {@code spReflectionVariableLayout_getStage}. */
    public int getStage() {
        return SlangReflectionAPI.spReflectionVariableLayout_getStage(self);
    }

    /** Calls {@code spReflectionVariableLayout_GetTypeLayout}. */
    public TypeLayoutReflection getTypeLayout() {
        MemorySegment result = SlangReflectionAPI.spReflectionVariableLayout_GetTypeLayout(self);
        return result.address() == 0 ? null : new TypeLayoutReflection(result, owner);
    }

    /** Calls {@code spReflectionVariableLayout_GetVariable}. */
    public VariableReflection getVariable() {
        MemorySegment result = SlangReflectionAPI.spReflectionVariableLayout_GetVariable(self);
        return result.address() == 0 ? null : new VariableReflection(result, owner);
    }

}
