// GENERATED by slang-bindgen from api/slang-api.json (Slang 2026.13). DO NOT EDIT.
// Regenerate: see CLAUDE.md / DESIGN.md §9.
package io.github.refux.slang;

import io.github.refux.slang.ffi.SlangNative;
import io.github.refux.slang.ffi.gen.SlangReflectionAPI;
import java.lang.foreign.Arena;
import java.lang.foreign.MemorySegment;

/**
 * Generated base of {&#64;code slang::VariableReflection}: each method forwards to the spReflection* downcall that slang.h's inline C++ wrapper compiles to. Reflection data is owned by the component/session it came from; the {&#64;code owner} reference keeps that owner reachable. The hand-written subclass {&#64;code VariableReflection} adds ergonomics.
 */
public abstract class VariableReflectionGen {
    final MemorySegment self;
    final Object owner;

    VariableReflectionGen(MemorySegment self, Object owner) {
        this.self = self;
        this.owner = owner;
    }

    /** The raw native reflection pointer (borrowed; owned by the program). */
    public final MemorySegment segment() {
        return self;
    }

    /** Calls {@code spReflectionVariable_applySpecializations}. */
    public VariableReflection applySpecializations(GenericReflection generic) {
        MemorySegment result = SlangReflectionAPI.spReflectionVariable_applySpecializations(self, (generic == null ? MemorySegment.NULL : generic.self));
        return result.address() == 0 ? null : new VariableReflection(result, owner);
    }

    /** Calls {@code spReflectionVariable_FindUserAttributeByName}. */
    public Attribute findAttributeByName(MemorySegment globalSession, String name) {
        try (Arena arena = Arena.ofConfined()) {
            MemorySegment result = SlangReflectionAPI.spReflectionVariable_FindUserAttributeByName(self, globalSession, arena.allocateFrom(name));
            return result.address() == 0 ? null : new Attribute(result, owner);
        }
    }

    /** Calls {@code spReflectionVariable_FindModifier}. */
    public MemorySegment findModifier(int modifierID) {
        return SlangReflectionAPI.spReflectionVariable_FindModifier(self, modifierID);
    }

    /** Calls {@code spReflectionVariable_GetDefaultValueFloat}. */
    public int getDefaultValueFloat(MemorySegment rs) {
        return SlangReflectionAPI.spReflectionVariable_GetDefaultValueFloat(self, rs);
    }

    /** Calls {@code spReflectionVariable_GetDefaultValueInt}. */
    public int getDefaultValueInt(MemorySegment rs) {
        return SlangReflectionAPI.spReflectionVariable_GetDefaultValueInt(self, rs);
    }

    /** Calls {@code spReflectionVariable_GetGenericContainer}. */
    public GenericReflection getGenericContainer() {
        MemorySegment result = SlangReflectionAPI.spReflectionVariable_GetGenericContainer(self);
        return result.address() == 0 ? null : new GenericReflection(result, owner);
    }

    /** Calls {@code spReflectionVariable_GetName}. */
    public String getName() {
        return SlangNative.readUtf8(SlangReflectionAPI.spReflectionVariable_GetName(self));
    }

    /** Calls {@code spReflectionVariable_GetType}. */
    public TypeReflection getType() {
        MemorySegment result = SlangReflectionAPI.spReflectionVariable_GetType(self);
        return result.address() == 0 ? null : new TypeReflection(result, owner);
    }

    /** Calls {@code spReflectionVariable_GetUserAttribute}. */
    public Attribute getUserAttributeByIndex(int index) {
        MemorySegment result = SlangReflectionAPI.spReflectionVariable_GetUserAttribute(self, index);
        return result.address() == 0 ? null : new Attribute(result, owner);
    }

    /** Calls {@code spReflectionVariable_GetUserAttributeCount}. */
    public int getUserAttributeCount() {
        return SlangReflectionAPI.spReflectionVariable_GetUserAttributeCount(self);
    }

    /** Calls {@code spReflectionVariable_HasDefaultValue}. */
    public boolean hasDefaultValue() {
        return SlangReflectionAPI.spReflectionVariable_HasDefaultValue(self);
    }

}
